# for conculture creation
# some principles may conflict, but this is why they are ranked
# it will be interesting to figure out how to reconcile conflicting principles based on which is more important


import random


cultural_principles = [
    "The physical world will help you.",
    "The physical world will hurt you.",
    "The individual good matters.",
    "The collective good matters.",
    "The mind and body are separate.",
    "The mind exists as a part of the body.",
    "Every person is equal.",
    "Some people don't have minds.",
    "Only I have a mind.",
    "There is no self.",
    "All people are a collective consciousness.",
    "Things tend toward order.",
    "Things tend toward disorder.",
    "Biological life is precious, fragile, and rare.",
    "Biological life is inevitable and shows up spontaneously.",
    "We can tell what each other are thinking to some extent.",
    "We can never know what others are thinking.",
    "We are all thinking variations of the same thing.",
    "There are planes of existence parallel to ours.",
    "Our world is the only plane of existence.",
    "There are multiple possible realities, parallel timelines.",
    "There is only one timeline, which is ours.",
    "The past and the future do not exist.",
    "All times exist equally; we just find ourselves at a certain point.",
    "It is possible to gain information about other timelines.",
    "We can never know what would happen in another timeline.",
    "It is possible to influence which timeline you end up in.",
    "We have no control over how things turn out.",
    "Animals have minds.",
    "Plants have minds.",
    "Non-living objects have minds.",
    "Time only appears to pass, but the timeline exists statically, as if we are walking along a road.",
    "Time flows past us, as if we are standing in a river.",
    "The world rewards good deeds and punishes bad ones.",
    "The world is indifferent to our deeds.",
    "Diversity is good.",
    "Diversity is bad.",
    "Things repeat themselves.",
    "New things are always happening.",
    "There is limited space in our minds.",
    "There is unlimited space in our minds.",
    "Opportunities for happiness are abundant.",
    "Opportunities for happiness are scarce.",
    "Physical resources are abundant.",
    "Physical resources are scarce.",
    "The mind is fragile.",
    "The mind is resilient.",
    "Beliefs should be malleable.",
    "Beliefs should be rigid.",
    "There is no afterlife.",
    "There is an afterlife in a separate world.",
    "Life is cyclical; the afterlife is another life in this world.",
    "Each time you wake up, you could wake up as a different person and will have their mind and memories.",
    "The world has always existed.",
    "The world was created at some point.",
    "The world will be destroyed at some point.",
    "The world will always exist.",
    "The autonomy of others should be respected.",
    "The autonomy of others can be breached with good reason.",
    "The autonomy of others does not matter.",
    "One should be careful not to offend others.",
    "Others are responsible for their own feelings, and you do not have to change your behavior for them.",
    "One should try to make others happy.",
    "One should do whatever makes oneself happy.",
    "One should not hurt others.",
    "It is okay for the strong to hurt the weak.",
    "The strong are obligated to help the weak.",
    "Cultural change is good.",
    "Cultural change is bad.",
    "Revenge is justified.",
    "Revenge only serves to make things even worse.",
    "People can change dramatically.",
    "People can learn and change, but they will always retain some aspects of their original self.",
    "People can never change.",
    "Some people should have more power.",
    "All people should have equal power.",  
    "Everyone can make decisions for themselves.",
    "Some people need to be controlled.",
    "Keeping families together and strong is important.",
    "People should be encouraged to go their own way.",
    "There are many relationships which can be made at any point in life.",
    "There are very few rewarding relationships to be had; they are rare.",
    "Relationships will come and go over time.",
    "Close relationships should be maintained forever.",
    "People's worth is determined by their past actions.",
    "People's worth is determined by who they associate with.",
    "People are equally worthy no matter what.",
    "People's worth is determined by their present actions, but not their past.",
    "We should try to predict what people are going to do.",
    "It is impossible to predict what someone is going to do.",
    "We should protect ourselves against risk.",
    "Risk is neither good nor bad; it is just a part of the world.",
    "Risk is a good thing and should be embraced.",
    "The present matters more than the future.",
    "The future matters more than the present.",
    "The present and the future matter equally.",
    "Things get better over time.",
    "Things get worse over time.",
    "Things do not get better or worse in the long run.",
    "Things could get better or worse in the long run, but we don't know which.",
    "Mental states are more real than the physical world.",
    "The physical world is more real than mental states.",
    "Mental and physical things are equally real.",
    "Resources need to be protected.",
    "Resources need to be shared.",
    "Death is to be feared.",
    "Death is a release from the hardships of the world.",
    "Everyone should have the opportunity to live their best life for themselves.",
    "Everyone should use their life for the betterment of the community.",
    "There are supernatural beings.",
    "The world does things in a thinking way.",
    "The world has goals.",
    "The world is unthinking and just follows rules.",
    "The world has no goals.",
    "Everything in the world can ultimately be understood.",
    "There are things in the world that we can never understand.",
    "A person innately knows everything about themself.",
    "A person must learn about themself over time.",
    "A person can never truly understand themself.",
    "A person can innately understand others.",
    "A person must learn about others over time.",
    "A person can never truly understand others.",
    "Conceiving of something makes it more real, and creates potential for it to become physical.",
    "Speaking about something makes it more real, and createse potential for it to become physical.",
    "Animals can understand human communication.",
    "The world is static overall.",
    "The world is dynamic and can change drastically.",
    "People have a large degree of control over the physical world.",
    "People do not have much control over the physical world.",
    "The unknown is to be feared.",
    "The unknown is to be embraced.",
    "Changes in beliefs turn you into a different person.",
    "Changes in beliefs do not change who you are.",
    "Nature can be tamed.",
    "We should want to tame nature.",
    "Nature cannot be tamed.",
    "We should not attempt to tame nature.",
    "Anyone can learn anything.",
    "Some people cannot learn anything new.",
    "There are some things that some people cannot learn.",
    "People should use language as clearly as possible.",
    "People should speak indirectly.",
    "Misunderstandings are the fault of the speaker.",
    "Misunderstandings are the fault of the listener.",
    "Misunderstandings are the fault of both the speaker and the listener.",
    "One should respect the commands of authority figures.",
    "No one has any more authority than anyone else.",
    "Telling someone what to do is an act of caring for them.",
    "Telling someone what to do is a breach of their autonomy.",
    "Predecessors are wiser.",
    "Predecessors are stuck in old ways.",
    "Children's potential can be determined from an early age.",
    "You never know someone's potential; they could always surprise you.",
    "People's worth is determined by how well they treat others.",
    "People's worth is determined by how effectively they can get what they want for themselves.",
    "We should not assign different amounts of worth to people.",
    "Animals can be trusted to be safe around people.",
    "Animals are always wild and pose some risk.",
    "The inner workings of the mind are under a person's control.",
    "The inner workings of the mind are autonomous and cannot be controlled.",
    "Actions reflect who a person really is.",
    "Actions may be aberrations from who a person really is.",
    "People should learn a variety of skills.",
    "People should learn a small number of skills well.",
    "People should be self-sufficient.",
    "People should rely on each other for survival.",
    "The inner workings of the mind follow rules.",
    "The inner workings of the mind are lawless.",
    "One should not interrupt others.",
    "One should make oneself heard, even at others' expense.",
    "Listening is more important than talking.",
    "Talking is more important than listening.",
    "Listening and talking are equally important.",
    "Natural events mirror events in human affairs.",
    "Natural events are premonitions of things to come.",
    "Things can change very quickly.",
    "Things change only gradually.",
    "Everyone's opinion is equally valid.",
    "An opinion's validity is determined by its resemblance to fact.",
    "An opinion's validity is determined by its usefulness to the community.",
    "An opinion's validity is determined by its usefulness to the individual.",
    "Opinions should be expressed.",
    "Opinions should be kept to oneself.",
    "Peace is more important than justice.",
    "Justice is more important than peace.",
    "Justice and peace are equally important.",
    "The strong have the obligation to keep order.",
    "The weak have the obligation to work harder and become stronger.",
    "Everyone should try new things often.",
    "People should stick to what they know best.",
    "People should try to see the world in others' shoes.",
    "You can never know what it is like to be someone else.",
    "Others' experiences are very similar to your own.",
    "Fears should be confronted.",
    "Fears are useful warnings and should be heeded.",
    "Sadness is a valuable emotion for everyone to experience.",
    "Sadness is to be avoided in order to live better.",
    "Some things are physically impossible.",
    "Anything conceivable is physically possible.",
    "There are things which are physically possible but inconceivable.",
    "The physical world has emotions similar to human ones.",
    "The physical world will reward or punish human actions.",
    "There are invisible beings which pervade the world.",
    "What we can sense is all that is real.",
    "Life is to be enjoyed.",
    "Life is to be endured.",
    "No one has any social obligations.",
    "People have social obligations to their community.",
    "All features of a person are orthogonal to each other.",
    "Some features of a person are correlated, and others are orthogonal.",
    "All features of a person are correlated.",
    "Time heals all wounds.",
    "Some emotional pain stays with a person forever.",
    "Causing emotional pain is just as bad as causing physical pain.",
    "Causing emotional pain is worse than causing physical pain.",
    "Causing physical pain is worse than causing emotional pain.",
    "We can infer causality from observation.",
    "We can never be sure of the causes of an event.",
    "Truths can be found by thought alone.",
    "Truths can only be found by experimenting in the real world.",
    "Lying is an acceptable way to achieve one's ends.",
    "Lying is never acceptable.",
    "If you do something for someone else, that person now owes you.",
    "People do not owe each other for good deeds.",
    "The dead should be respected.",
    "The dead should not be spoken of.",
    "The dead deserve no more respect than they did during their lifetimes.",
    "One should respect parents' wishes.",
    "Children will do as they please.",
    "Those with means should help those in need.",
    "Everyone should fend for themselves.",
    "Appearances are deceiving.",
    "Appearances can be trusted.",
]


def get_ranked_principles(n_principles):
    sample = random.sample(cultural_principles, n_principles)  # sample returns ordered list, in random order, not sorted
    return [(i+1, x) for i,x in enumerate(sample)]


if __name__ == "__main__":
    print("Cultural principles in order of importance:")
    for l in get_ranked_principles(5):
        print("{}. {}".format(*l))
