# for conculture creation
# some principles may conflict, but this is why they are ranked
# it will be interesting to figure out how to reconcile conflicting principles based on which is more important


import random


cultural_principles = [
    "The physical world will help you.",
    "The physical world will hurt you.",
    "The individual good matters.",
    "The collective good matters.",
    "The mind and body are separate.",
    "The mind exists as a part of the body.",
    "Every person is equal.",
    "Some people don't have minds.",
    "Only I have a mind.",
    "There is no self.",
    "All people are a collective consciousness.",
    "Things tend toward order.",
    "Things tend toward disorder.",
    "Biological life is precious, fragile, and rare.",
    "Biological life is inevitable and shows up spontaneously.",
    "We can tell what each other are thinking to some extent.",
    "We can never know what others are thinking.",
    "We are all thinking variations of the same thing.",
    "There are planes of existence parallel to ours.",
    "Our world is the only plane of existence.",
    "There are multiple possible realities, parallel timelines.",
    "There is only one timeline, which is ours.",
    "The past and the future do not exist.",
    "All times exist equally; we just find ourselves at a certain point.",
    "It is possible to gain information about other timelines.",
    "We can never know what would happen in another timeline.",
    "It is possible to influence which timeline you end up in.",
    "We have no control over how things turn out.",
    "Animals have minds.",
    "Plants have minds.",
    "Non-living objects have minds.",
    "Time only appears to pass, but the timeline exists statically, as if we are walking along a road.",
    "Time flows past us, as if we are standing in a river.",
    "The world rewards good deeds and punishes bad ones.",
    "The world is indifferent to our deeds.",
    "Diversity is good.",
    "Diversity is bad.",
    "Things repeat themselves.",
    "New things are always happening.",
    "There is limited space in our minds.",
    "There is unlimited space in our minds.",
    "Opportunities for happiness are abundant.",
    "Opportunities for happiness are scarce.",
    "Physical resources are abundant.",
    "Physical resources are scarce.",
    "The mind is fragile.",
    "The mind is resilient.",
    "Beliefs should be malleable.",
    "Beliefs should be rigid.",
    "There is no afterlife.",
    "There is an afterlife in a separate world.",
    "Life is cyclical; the afterlife is another life in this world.",
    "Each time you wake up, you could wake up as a different person and will have their mind and memories.",
    "The world has always existed.",
    "The world was created at some point.",
    "The world will be destroyed at some point.",
    "The world will always exist.",
    "The autonomy of others should be respected.",
    "The autonomy of others can be breached with good reason.",
    "The autonomy of others does not matter.",
    "One should be careful not to offend others.",
    "Others are responsible for their own feelings, and you do not have to change your behavior for them.",
    "One should try to make others happy.",
    "One should do whatever makes oneself happy.",
    "One should not hurt others.",
    "It is okay for the strong to hurt the weak.",
    "The strong are obligated to help the weak.",
    "Cultural change is good.",
    "Cultural change is bad.",
    "Revenge is justified.",
    "Revenge only serves to make things even worse.",
    "People can change dramatically.",
    "People can learn and change, but they will always retain some aspects of their original self.",
    "People can never change.",
    "Some people should have more power.",
    "All people should have equal power.",  
    "Everyone can make decisions for themselves.",
    "Some people need to be controlled.",
    "Keeping families together and strong is important.",
    "People should be encouraged to go their own way.",
    "There are many relationships which can be made at any point in life.",
    "There are very few rewarding relationships to be had; they are rare.",
    "Relationships will come and go over time.",
    "Close relationships should be maintained forever.",
    "People's worth is determined by their past actions.",
    "People's worth is determined by who they associate with.",
    "People are equally worthy no matter what.",
    "People's worth is determined by their present actions, but not their past.",
    "We should try to predict what people are going to do.",
    "It is impossible to predict what someone is going to do.",
    "We should protect ourselves against risk.",
    "Risk is neither good nor bad; it is just a part of the world.",
    "Risk is a good thing and should be embraced.",
    "The present matters more than the future.",
    "The future matters more than the present.",
    "The present and the future matter equally.",
    "Things get better over time.",
    "Things get worse over time.",
    "Things do not get better or worse in the long run.",
    "Things could get better or worse in the long run, but we don't know which.",
    "Mental states are more real than the physical world.",
    "The physical world is more real than mental states.",
    "Mental and physical things are equally real.",
    "Resources need to be protected.",
    "Resources need to be shared.",
    "Death is to be feared.",
    "Death is a release from the hardships of the world.",
    "Everyone should have the opportunity to live their best life for themselves.",
    "Everyone should use their life for the betterment of the community.",
    "There are supernatural beings.",
    "The world does things in a thinking way.",
    "The world has goals.",
    "The world is unthinking and just follows rules.",
    "The world has no goals.",
    "Everything in the world can ultimately be understood.",
    "There are things in the world that we can never understand.",
    "A person innately knows everything about themself.",
    "A person must learn about themself over time.",
    "A person can never truly understand themself.",
    "A person can innately understand others.",
    "A person must learn about others over time.",
    "A person can never truly understand others.",
    "Conceiving of something makes it more real, and creates potential for it to become physical.",
    "Speaking about something makes it more real, and createse potential for it to become physical.",
    "Animals can understand human communication.",
    "The world is static overall.",
    "The world is dynamic and can change drastically.",
    "People have a large degree of control over the physical world.",
    "People do not have much control over the physical world.",
    "The unknown is to be feared.",
    "The unknown is to be embraced.",
    "Changes in beliefs turn you into a different person.",
    "Changes in beliefs do not change who you are.",
    "Nature can be tamed.",
    "We should want to tame nature.",
    "Nature cannot be tamed.",
    "We should not attempt to tame nature.",
    "Anyone can learn anything.",
    "Some people cannot learn anything new.",
    "There are some things that some people cannot learn.",
    "People should use language as clearly as possible.",
    "People should speak indirectly.",
    "Misunderstandings are the fault of the speaker.",
    "Misunderstandings are the fault of the listener.",
    "Misunderstandings are the fault of both the speaker and the listener.",
    "One should respect the commands of authority figures.",
    "No one has any more authority than anyone else.",
    "Telling someone what to do is an act of caring for them.",
    "Telling someone what to do is a breach of their autonomy.",
    "Predecessors are wiser.",
    "Predecessors are stuck in old ways.",
    "Children's potential can be determined from an early age.",
    "You never know someone's potential; they could always surprise you.",
    "People's worth is determined by how well they treat others.",
    "People's worth is determined by how effectively they can get what they want for themselves.",
    "We should not assign different amounts of worth to people.",
    "Animals can be trusted to be safe around people.",
    "Animals are always wild and pose some risk.",
    "The inner workings of the mind are under a person's control.",
    "The inner workings of the mind are autonomous and cannot be controlled.",
    "Actions reflect who a person really is.",
    "Actions may be aberrations from who a person really is.",
    "People should learn a variety of skills.",
    "People should learn a small number of skills well.",
    "People should be self-sufficient.",
    "People should rely on each other for survival.",
    "The inner workings of the mind follow rules.",
    "The inner workings of the mind are lawless.",
    "One should not interrupt others.",
    "One should make oneself heard, even at others' expense.",
    "Listening is more important than talking.",
    "Talking is more important than listening.",
    "Listening and talking are equally important.",
    "Natural events mirror events in human affairs.",
    "Natural events are premonitions of things to come.",
    "Things can change very quickly.",
    "Things change only gradually.",
    "Everyone's opinion is equally valid.",
    "An opinion's validity is determined by its resemblance to fact.",
    "An opinion's validity is determined by its usefulness to the community.",
    "An opinion's validity is determined by its usefulness to the individual.",
    "Opinions should be expressed.",
    "Opinions should be kept to oneself.",
    "Peace is more important than justice.",
    "Justice is more important than peace.",
    "Justice and peace are equally important.",
    "The strong have the obligation to keep order.",
    "The weak have the obligation to work harder and become stronger.",
    "Everyone should try new things often.",
    "People should stick to what they know best.",
    "People should try to see the world in others' shoes.",
    "You can never know what it is like to be someone else.",
    "Others' experiences are very similar to your own.",
    "Fears should be confronted.",
    "Fears are useful warnings and should be heeded.",
    "Sadness is a valuable emotion for everyone to experience.",
    "Sadness is to be avoided in order to live better.",
    "Some things are physically impossible.",
    "Anything conceivable is physically possible.",
    "There are things which are physically possible but inconceivable.",
    "The physical world has emotions similar to human ones.",
    "The physical world will reward or punish human actions.",
    "There are invisible beings which pervade the world.",
    "What we can sense is all that is real.",
    "Life is to be enjoyed.",
    "Life is to be endured.",
    "No one has any social obligations.",
    "People have social obligations to their community.",
    "All features of a person are orthogonal to each other.",
    "Some features of a person are correlated, and others are orthogonal.",
    "All features of a person are correlated.",
    "Time heals all wounds.",
    "Some emotional pain stays with a person forever.",
    "Causing emotional pain is just as bad as causing physical pain.",
    "Causing emotional pain is worse than causing physical pain.",
    "Causing physical pain is worse than causing emotional pain.",
    "We can infer causality from observation.",
    "We can never be sure of the causes of an event.",
    "Truths can be found by thought alone.",
    "Truths can only be found by experimenting in the real world.",
    "Lying is an acceptable way to achieve one's ends.",
    "Lying is never acceptable.",
    "If you do something for someone else, that person now owes you.",
    "People do not owe each other for good deeds.",
    "The dead should be respected.",
    "The dead should not be spoken of.",
    "The dead deserve no more respect than they did during their lifetimes.",
    "One should respect parents' wishes.",
    "Children will do as they please.",
    "Those with means should help those in need.",
    "Everyone should fend for themselves.",
    "Appearances are deceiving.",
    "Appearances can be trusted.",
    "People must control their animal instincts.",
    "People must embrace their animal instincts.",
    "An eye for an eye.",
    "Those who are harmful to the community must be expelled.",
    "Those who are harmful to the community must be rehabilitated.",
    "There is an objective truth which exists through all time.",
    "There is an objective truth which changes over time.",
    "There is no objective truth.",
    "Some people have more ability to see the inner workings of the world than others.",
    "All people are equally able to have insights into the inner workings of the world.",
    "People are a product of the environment in which they find themselves.",
    "People have innate characteristics regardless of environment.",
    "Stories contain information about the past.",
    "Stories contain information about how to live well.",
    "Sight is more trustworthy than sound.",
    "Sound is more trustworthy than sight.",
    "Sight and sound are both very important for understanding the world.",
    "People must use their own senses to determine the truth.",
    "People must listen to their peers to determine the truth.",
    "Whether something really happened does not matter as much as the implications it would have if it did happen.",
    "Food is the best kind of gift to give.",
    "Money is the best kind of gift to give.",
    "Loyalty is the basis of strong relationships.",
    "You should stand up for anyone in need.",
    "You should only help people in need if it serves your interests.",
    "You should not help anyone in need; it is their job to help themselves.",
    "Physical intimacy is the basis of strong relationships.",
    "Entertaining conversation is the basis of strong relationships.",
    "You should choose your friends based on how much they can improve your economic situation.",
    "You should choose your friends based on how good they make you feel about yourself.",
    "You should choose your friends based on how much you have in common.",
    "You should choose your friends based on whatever random interactions the universe gives you.",
    "The events of everyday life follow predictable patterns.",
    "The events of everyday life are inherently random.",
    "Physical assault is an attack on a person's autonomy.",
    "Physical assault is an acceptable way to resolve disputes.",
    "Physical assault is an acceptable way for anyone to behave toward anyone else.",
    "What someone does when overcome by emotion is still their fault.",
    "What someone does when overcome by emotion is no one's fault.",
    "What someone does when overcome by emotion is the fault of whoever caused the emotion.",
    "People should avoid showing anger.",
    "People should avoid showing sadness.",
    "People should avoid showing happiness.",
    "People should avoid showing any emotion at all.",
    "People should openly show emotion.",
    "People will likely fake emotions in order to further their personal goals.",
    "The emotions which people show are genuine.",
    "Friendships must be maintained through frequent interaction.",
    "Friendships may lie dormant for long periods of time and then be resumed when the people meet again.",
    "Romantic relationships must be maintained through frequent interaction.",
    "Romantic relationships may lie dormant for long periods of time and then be resumed when the people meet again.",
    "There is a correct way to view the world.",
    "Those with more power have the more correct way of viewing the world.",
    "There is no correct way to view the world.",
    "Those with more power are more likely to have distorted ways of viewing the world.",
    "People are not themselves when they are overcome by emotion.",
    "People show their most genuine selves when they are overcome by emotion.",
    "People's appearances can provide insight into what kind of people they are.",
    "A person's appearance has nothing to do with the kind of person they are.",
    "A person's private life should remain private.",
    "No one should separate their private and public lives; all of it should be public.",
    "People should be treated differently based on how much power they have.",
    "People should be treated differently based on what they have done in the past.",
    "People should be treated differently based on how old they are.",
    "People should all be treated basically the same.",
    "People should put the most energy into the most important relationship in their lives.",
    "People should put energy into all the relationships which they wish to keep.",
    "Energy is the antidote to entropy.",
    "The use of energy contributes to the rise in entropy.",
    "Energy is never wasted.",
    "Violence is a part of everyday life.",
    "Violence is never the answer.",
    "Highly educated people think they are better than others.",
    "Highly educated people should be trusted to make decisions that affect the community.",
    "People who think they are better than others need to be punished.",
    "People who think they are better than others need to be exposed to diversity so they can learn.",
    "People who think they are better than others have good reason for this belief, and should be treated as if they are better.",
    "No one is better than anyone else, either inherently or through acquisition of any trait.",
    "Agriculture is the best way to feed the community sustainably.",
    "Hunting is the best way to feed the community sustainably.",
    "Sustainability of a way of life is very important.",
    "If a way of life is not sustainable, we can always go somewhere else and use those resources, so sustainability doesn't matter.",
    "Depicting someone is an act of honoring them.",
    "Depicting someone is an insult to their true essence.",
    "Songs, stories, etc., are common goods and can be passed around freely.",
    "Songs, stories, etc., are intellectual property of the one who created them.",
    "One should brag about their accomplishments.",
    "One should be modest about their accomplishments.",
    "Accomplishments are attributed to the one who did the most work.",
    "Accomplishments are attributed to everyone who contributed.",
    "No discovery or accomplishment is done alone.",
    "An accomplishment should attributed to the one who was first to be publicly seen having accomplished it.",
    "Every day in which life continues without trouble is cause for celebration.",
    "Life is mostly suffering.",
    "Life is mostly smooth sailing.",
    "Large physical objects are powerful entities which should be respected and feared.",
    "Children are wise due to being uncorrupted by the world.",
    "Children are foolish due to knowing little about the world.",
    "Language is inadequate to express thoughts in full depth.",
    "Language can be used masterfully to express any amount of depth of thought.",
    "Meals are the best setting for socializing.",
    "Undertaking projects is the best setting for socializing.",
    "One should not speak to another without the intent to have a full conversation.",
    "Just because someone first speaks to another does not mean they want to have a full conversation.",
    "You should always speak to people you encounter, even if only a little.",
    "Physical feats are good challenges for personal growth.",
    "Intellectual feats are good challenges for personal growth.",
    "Emotional feats are good challenges for personal growth.",
    "Physical prowess is indicative of mental strength.",
    "Physical prowess and mental strength are unrelated.",
    "Different communities should trade openly.",
    "Different communities should mostly be self-sufficient.",
    "Cultural diffusion is good.",
    "Cultural diffusion is bad.",
    "Literacy is important for the transmission of knowledge.",
    "Speaking and listening are important for the transmission of knowledge.",
    "Knowledge transmission is not very important; newer generations should find things out on their own.",
    "Multiple people can have the same idea independently.",
    "Every idea ultimately has an original creator to which it should be attributed.",
    "Those who know most about the supernatural should be leaders.",
    "Those who know most about the physical world should be leaders.",
    "Those who know most about social issues should be leaders.",
    "There should be no leaders.",
    "People should share leadership of the community, and each should lead in the facet of life which they know the most about.",
    "People should take turns leading, and this should be done in an egalitarian way.",
    "People should take turns leading, and exchange of power should be determined by combat.",
    "People should take turns leading, and exchange of power should be done by intellectual debate.",
    "The intent behind a crime matters for determining the punishment.",
    "Only the effect of a crime, not its intent, matters for determining the punishment.",
    "People of another group are interchangeable in terms of revenge; any of them can be punished for the crimes of any other.",
    "Revenge should only be had on the person who committed a crime.",
    "Revenge should not exist.",
    "A person's social relationships drive their actions.",
    "A person's internal characteristics drive their actions.",
    "No one is in control of their own actions.",
    "People are in control of their own actions.",
    "Everyone is responsible for maintaining public spaces.",
    "No one is responsible for maintaining public spaces.",
    "The leaders are responsible for maintaining public spaces.",
    "There should be a single leader.",
    "There should be a group of leaders.",
    "There should not be any leaders.",
    "People should take turns being the leader.",
    "There should be different leaders for different issues based on who knows the most about the issue.",
    "One should be loyal to one's kin first.",
    "One should not show any loyalty to one group over another.",
    "Things in nature do not belong to anyone and must be shared.",
    "Nothing belongs to anyone; private property does not exist.",
    "Anything, including things in nature, can be owned privately.",

]


def get_ranked_principles(n_principles):
    sample = random.sample(cultural_principles, n_principles)  # sample returns ordered list, in random order, not sorted
    return [(i+1, x) for i,x in enumerate(sample)]


if __name__ == "__main__":
    print("Cultural principles in order of importance:")
    for l in get_ranked_principles(5):
        print("{}. {}".format(*l))
