# create stuff from the genome
# and this stuff will in turn do chemistry / ecology things

# take certain substrings and walk a path based on them
# 1 = go forward; 0 = turn left (starting from standard position)
# then get some numbers based on this path
# min/max x/y visited
# max/avg distance from origin
# these numbers are the chemical properties of the "proteins" made by the DNA substrings


import random
import numpy as np
import matplotlib.pyplot as plt
import functools

import RawVariation as rv
from OrganicChemical import OrganicChemical


def get_some_chemicals(dna):
    # don't get all substrings
    # start somewhere random, have bias toward shorter strings (exponential decay of how long you'll keep transcribing)
    expected_n = len(dna)
    should_transcribe = lambda: random.random() > 1 / expected_n
    expected_len = 10
    get_next_base = lambda: random.random() > 1 / expected_len
    while should_transcribe():
        i = random.randrange(len(dna))
        s = []
        while get_next_base():
            s.append(dna[i])
            i += 1
            if i >= len(dna):
                break
        chemical = get_chemical_from_substring(s)
        yield chemical


def get_all_chemicals(dna):
    return set(get_chemical_from_substring(s) for s in get_all_substrings(dna))


def get_all_substrings(dna):
    n = len(dna)
    for i in range(n):
        max_len = n - i
        for l in range(1, max_len + 1):
            yield tuple(dna[i : i + l])


def get_path_from_substring(arr):
    x,y = 0, 0
    res = [(x, y)]
    direction = 0
    for bit in arr:
        if bit == 0:
            direction = (direction + 90) % 360
        else:
            dx = 1 if direction == 0 else -1 if direction == 180 else 0
            dy = 1 if direction == 90 else -1 if direction == 270 else 0
            x += dx
            y += dy
            res.append((x,y))
    # print(f"arr {arr} gave path {res}")
    return res


def get_chemical_from_substring(arr):
    path = get_path_from_substring(arr)
    return OrganicChemical.from_path(path)


def simulate_chemical_reactions(chemicals):
    # pick two random molecules, so more common ones will bump into each other more often
    a,b = random.sample(chemicals, 2)
    # something about they will be attracted if their horizontalities are large and in opposite directions
    # similar with verticality, it acts like a different fundamental force but has same effect
    # larger mass makes the reaction take more energy
    raise NotImplementedError




if __name__ == "__main__":
    dnas = [rv.get_dna(1000) for i in range(100)]

    chem0, = get_all_chemicals([0])
    assert chem0.name == "orinan"
    chem1, = get_all_chemicals([1])
    assert chem1.name == "R-cretinan"

    all_chemicals = set()
    for dna in dnas:
        counts = {}
        for chemical in get_some_chemicals(dna):
            if chemical not in counts:
                counts[chemical] = 0
            counts[chemical] += 1
            if chemical not in all_chemicals:
                chemical.plot()
                all_chemicals.add(chemical)
        print(f"\nDNA string:\n{rv.get_dna_str(dna)}\nproduced chemicals:")
        for chemical, count in sorted(counts.items(), key=lambda kv: kv[1], reverse=True):
            print(f"{count} units of {chemical}")

# how should chemicals behave? some numbers can determine whether / how often they will react with each other
# reactions should produce a result that has some new properties based on the reactants
# environment that organisms live in should have some effect on both the organism and the chemicals
# e.g. heat can speed up the decomposition of chemicals, aid metabolism, trigger certain reactions, etc.

# how should chemicals affect organisms? I think having them be the vector for ecological dynamics will be easiest
# basically the organisms interact through exchange of chemicals and then some can kill others or such by causing certain reactions
# so the chemicals that are around an organism should affect whether it can reproduce
# some could be mutagens, changing the rate of mutation in DNA transcription
# maybe some chemicals can exist in the environment but aren't made by biology (no DNA sequence can make that path)

# idea: the chemical generated by the substring "0" IS the nucleotide 0, simil for 1
# that way the nucleotides can interact with chemicals around them, so some things will be poisonous
# 
